### ISSUE TITLE
authorization error

### ISSUE THREAD

**Issue by MihaiCraciun88** [Ozoniuss/oblio-exporter#1]
Hi,

About the authorization error I think if you change the auth response to: 

type AuthResponse struct {
	Token       string `json:"access_token"`
	TokenType   string `json:"token_type"`
	Scope       string `json:"scope"`
}

will resolve the problem
Thank you

**Comment by Ozoniuss** [comment]
Seems to have worked. How come? This is just removing two fields, so I would've expected the marshaler to work anyway. Are ExpiredIn or RequestTime returned as a different data type from string the very first time?

btw, I think I will drop this solution and move to selenium, there only seems to be an API for retrieving issued invoices, but not received invoices

**Comment by MihaiCraciun88** [comment]
Yes, it is int for the first time
